# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:  [push, pull_request]
  #  push:
  #    branches: [ master ]
  #  pull_request:
  #    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17, 21, 22-ea]
        dist: ['zulu']
    name: Build and Verify with JDK ${{ matrix.dist }} ${{ matrix.java }}
    steps:
      - uses: ts-graphviz/setup-graphviz@v1
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.dist }} ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.dist }}
          java-version: ${{ matrix.java }}
      - name: Verify with Maven
        run: mvn -DperformRelease=true --batch-mode --no-transfer-progress clean verify failsafe:integration-test
